name: Seed Backlog

on:
  workflow_dispatch: {}

permissions:
  issues: write
  contents: read

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create milestones, labels, and issues from .github/backlog.json
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = '.github/backlog.json';
            const data = JSON.parse(fs.readFileSync(path, 'utf8'));

            // Ensure milestone map (title -> number)
            const existingMilestones = await github.paginate(github.rest.issues.listMilestones, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            const milestoneMap = new Map(existingMilestones.map(m => [m.title, m.number]));

            for (const m of data.milestones || []) {
              if (!milestoneMap.has(m.title)) {
                const created = await github.rest.issues.createMilestone({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: m.title,
                  description: m.description || ''
                });
                milestoneMap.set(created.data.title, created.data.number);
              }
            }

            // Ensure labels (with colors)
            const existingLabels = await github.paginate(github.rest.issues.listLabelsForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const labelSet = new Set(existingLabels.map(l => l.name));
            const labelColors = {
              bug: 'd73a4a',
              enhancement: 'a2eeef',
              task: 'bfdadc',
              ci: 'c5def5',
              database: 'f9d0c4',
              test: 'e4e669',
              files: 'fef2c0',
              search: 'a4f287',
              reporting: 'c2e0c6',
              notifications: 'cfd3ff',
              sso: 'c0ffee',
              security: 'b60205',
              performance: 'ffd78e',
              ops: 'd4c5f9',
              docs: '0075ca',
              api: '0366d6',
              frontend: '0e8a16',
              design: 'fbca04',
              M0: 'ededed', M1: 'ededed', M2: 'ededed', M3: 'ededed', M4: 'ededed', M5: 'ededed', M6: 'ededed'
            };
            const desired = new Set(Object.keys(labelColors));
            for (const name of desired) {
              if (!labelSet.has(name)) {
                await github.rest.issues.createLabel({ owner: context.repo.owner, repo: context.repo.repo, name, color: labelColors[name] || 'ededed' });
                labelSet.add(name);
              }
            }

            // Existing issues by title to avoid duplicates
            const existingIssues = await github.paginate(github.rest.issues.listForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all'
            });
            const byTitle = new Set(existingIssues.map(i => i.title));

            for (const issue of data.issues || []) {
              if (byTitle.has(issue.title)) continue; // skip duplicates by title
              const milestoneNumber = milestoneMap.get(issue.milestone) || undefined;
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: issue.title,
                body: issue.body || '',
                labels: issue.labels || [],
                milestone: milestoneNumber
              });
            }
